name: Accessibility Test & Report

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install the Reporter CLI
        env:
          apiKey: ${{ secrets.AGORA_API_KEY_KA }}
        run: |
          curl --compressed -H "X-JFrog-Art-Api: ${apiKey}" "https://agora.dequecloud.com/artifactory/devtools-npm/%40axe-devtools/reporter-cli/-/%40axe-devtools/reporter-cli-4.4.0.tgz" --output "reporter.tgz"
          tar -xvf "reporter.tgz"
      - name: Add Deque API Key
        env:
          dequeApiKey: ${{ secrets.DEQUE_API_KEY_KA }}
        run: |
          cd "$(pwd)/axe-devtools-ios-sample-app"
          echo "import Foundation
          struct Login {
            static let APIKey = \"${dequeApiKey}\"
          }" > "Login.swift"
      - name: Test
        run: |
          xcodebuild test -quiet -scheme "RegressionUITests" -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" -configuration Debug
      - name: Build Report
        env:
          scanFolderPath: ${{ '/Users/runner/RegressionScans' }}
        run: |
          package/pkgs/@axe-devtools/reporter-cli-macos ${scanFolderPath} "AxeReport" --format=html
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: axeDevTools Report
          path: AxeReport # or path/to/artifact

