# Sauce Labs config file for Real Devices

apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 1

xcuitest:
  app: "axe-devtools-ios-sample-app.ipa"
  testApp: "RegressionUITests-Runner.ipa"

suites:
  - name: "RegressionUITests"
    devices:
      - name: "iPhone.*"
        platformVersion: "17.7"
